name: Badge

on:
  push:
    tags:
      - "*"

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Time badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: time
          LABEL: "Updated at"
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 247BA0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Version badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: version
          LABEL: "Version"
          STATUS: ${{ steps.get-version.outputs.VERSION }}
          COLOR: 247BA0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
